// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: ROLORAN_TDeck_Neuhaus

#ifndef _ROLORAN_TDECK_NEUHAUS_UI_H
#define _ROLORAN_TDECK_NEUHAUS_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_ScreenSplash
void ui_ScreenSplash_screen_init(void);
extern lv_obj_t * ui_ScreenSplash;
extern lv_obj_t * ui_PanelSplashBackground;
extern lv_obj_t * ui_ImageSplashLogo;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenOANonCrisis
void ui_ScreenOANonCrisis_screen_init(void);
extern lv_obj_t * ui_ScreenOANonCrisis;
extern lv_obj_t * ui_LabelOANonCrisis;
extern lv_obj_t * ui_TextAreaOANonCrisis;
extern lv_obj_t * ui_ButtonOANCNav1;
extern lv_obj_t * ui_ButtonOANCNav2;
extern lv_obj_t * ui_ButtonOANCNav3;
extern lv_obj_t * ui_ButtonOANCNav4;
extern lv_obj_t * ui_LabelOANCNav1;
extern lv_obj_t * ui_LabelOANCNav2;
extern lv_obj_t * ui_LabelOANCNav3;
extern lv_obj_t * ui_LabelOANCNav4;
extern lv_obj_t * ui_OANCTextNum;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenOACrisis
void ui_ScreenOACrisis_screen_init(void);
extern lv_obj_t * ui_ScreenOACrisis;
extern lv_obj_t * ui_ButtonEMER;
extern lv_obj_t * ui_ButtonCIRE;
extern lv_obj_t * ui_LabelOACrisis;
extern lv_obj_t * ui_TextAreaOACrisis;
extern lv_obj_t * ui_LabelButtonEMER;
extern lv_obj_t * ui_LabelButtonCIRE;
extern lv_obj_t * ui_ButtonOACNav1;
extern lv_obj_t * ui_ButtonOACNav2;
extern lv_obj_t * ui_ButtonOACNav3;
extern lv_obj_t * ui_ButtonOACNav4;
extern lv_obj_t * ui_OACTextNum;
extern lv_obj_t * ui_LabelOACNav1;
extern lv_obj_t * ui_LabelOACNav2;
extern lv_obj_t * ui_LabelOACNav3;
extern lv_obj_t * ui_LabelOACNav4;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenEMER
void ui_ScreenEMER_screen_init(void);
extern lv_obj_t * ui_ScreenEMER;
extern lv_obj_t * ui_ButtonEMERSubmit;
extern lv_obj_t * ui_ButtonEMERAbort;
extern lv_obj_t * ui_LabelEMERButtonSubmit;
extern lv_obj_t * ui_LabelEMERButtonAbort;
extern lv_obj_t * ui_LabelEMERHeader;
extern lv_obj_t * ui_TextAreaEMERWho;
extern lv_obj_t * ui_TextAreaEMERWhere;
extern lv_obj_t * ui_TextAreaEMERWhat;
extern lv_obj_t * ui_LabelEMERWho;
extern lv_obj_t * ui_LabelEMERWhere;
extern lv_obj_t * ui_LabelEMERWhat;
extern lv_obj_t * ui_Label1;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenCIRE
void ui_ScreenCIRE_screen_init(void);
extern lv_obj_t * ui_ScreenCIRE;
extern lv_obj_t * ui_LabelCIREHeader;
extern lv_obj_t * ui_ButtonCIREsubmit;
extern lv_obj_t * ui_ButtonCIREabort;
extern lv_obj_t * ui_LabelButtonCIREsubmit;
extern lv_obj_t * ui_LabelButtonCIREabort;
extern lv_obj_t * ui_LabelCIREWho;
extern lv_obj_t * ui_LabelCIRECategory;
extern lv_obj_t * ui_LabelCIREFreetext;
extern lv_obj_t * ui_TextAreaCIREFreetext;
extern lv_obj_t * ui_TextAreaCIREWho;
extern lv_obj_t * ui_DropdownCIRECategory;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenMaintenance
void ui_ScreenMaintenance_screen_init(void);
extern lv_obj_t * ui_ScreenMaintenance;
extern lv_obj_t * ui_LabelMaintenanceMiddle;
extern lv_obj_t * ui_LabelMaintenanceTop;
extern lv_obj_t * ui_LabelMaintenanceBottom;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenRESP
void ui_ScreenRESP_screen_init(void);
extern lv_obj_t * ui_ScreenRESP;
extern lv_obj_t * ui_LabelRESPHeader1;
extern lv_obj_t * ui_ButtonRESPsubmit;
void ui_event_ButtonRESPabort(lv_event_t * e);
extern lv_obj_t * ui_ButtonRESPabort;
extern lv_obj_t * ui_LabelButtonRESPsubmit;
extern lv_obj_t * ui_LabelButtonRESPabort;
extern lv_obj_t * ui_LabelRESPFreetext;
extern lv_obj_t * ui_TextAreaRESPFreetext;
extern lv_obj_t * ui_TextAreaRESPoa;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenProvisioning
void ui_ScreenProvisioning_screen_init(void);
extern lv_obj_t * ui_ScreenProvisioning;
extern lv_obj_t * ui_LabelProvisioningMiddle;
extern lv_obj_t * ui_LabelProvisioningTop;
extern lv_obj_t * ui_LabelProvisioningBottom;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenEMER2
void ui_ScreenEMER2_screen_init(void);
extern lv_obj_t * ui_ScreenEMER2;
extern lv_obj_t * ui_ButtonEMERSubmit1;
extern lv_obj_t * ui_ButtonEMERAbort1;
extern lv_obj_t * ui_LabelEMERButtonSubmit1;
extern lv_obj_t * ui_LabelEMERButtonAbort1;
extern lv_obj_t * ui_LabelEMERHeader1;
extern lv_obj_t * ui_CIRE2SwitchLebensbedrohlich;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Dropdown2;
extern lv_obj_t * ui_CIRE2SwitchErsthelfer;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenEULA
void ui_ScreenEULA_screen_init(void);
extern lv_obj_t * ui_ScreenEULA;
extern lv_obj_t * ui_LabelMaintenanceMiddle1;
extern lv_obj_t * ui_LabelEULA1;
extern lv_obj_t * ui_EULAokButton;
extern lv_obj_t * ui_Label5;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_neuhaus_logo_png);    // assets/neuhaus_logo.png

// FONTS
LV_FONT_DECLARE(ui_font_Hack10);
LV_FONT_DECLARE(ui_font_Hack12);
LV_FONT_DECLARE(ui_font_Hack14);
LV_FONT_DECLARE(ui_font_Hack16);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
