// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: ROLORAN_TDeck_Neuhaus

#include "ui.h"

void ui_ScreenOACrisis_screen_init(void)
{
    ui_ScreenOACrisis = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenOACrisis, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonEMER = lv_btn_create(ui_ScreenOACrisis);
    lv_obj_set_width(ui_ButtonEMER, 146);
    lv_obj_set_height(ui_ButtonEMER, 45);
    lv_obj_set_x(ui_ButtonEMER, -81);
    lv_obj_set_y(ui_ButtonEMER, 97);
    lv_obj_set_align(ui_ButtonEMER, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonEMER, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonEMER, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonEMER, lv_color_hex(0xE04646), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonEMER, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonCIRE = lv_btn_create(ui_ScreenOACrisis);
    lv_obj_set_width(ui_ButtonCIRE, 146);
    lv_obj_set_height(ui_ButtonCIRE, 45);
    lv_obj_set_x(ui_ButtonCIRE, 81);
    lv_obj_set_y(ui_ButtonCIRE, 97);
    lv_obj_set_align(ui_ButtonCIRE, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonCIRE, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonCIRE, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelOACrisis = lv_label_create(ui_ScreenOACrisis);
    lv_obj_set_width(ui_LabelOACrisis, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelOACrisis, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelOACrisis, 0);
    lv_obj_set_y(ui_LabelOACrisis, -114);
    lv_obj_set_align(ui_LabelOACrisis, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelOACrisis, "Gemeinde Neuhaus          LoRa Notfall-Kommunikation");
    lv_obj_set_style_text_color(ui_LabelOACrisis, lv_color_hex(0xF30909), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelOACrisis, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelOACrisis, &ui_font_Hack10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextAreaOACrisis = lv_textarea_create(ui_ScreenOACrisis);
    lv_obj_set_width(ui_TextAreaOACrisis, 312);
    lv_obj_set_height(ui_TextAreaOACrisis, 128);
    lv_obj_set_x(ui_TextAreaOACrisis, 1);
    lv_obj_set_y(ui_TextAreaOACrisis, 2);
    lv_obj_set_align(ui_TextAreaOACrisis, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextAreaOACrisis, "Hier wird die jeweilige Nachricht angezeigt.");
    lv_obj_set_style_text_font(ui_TextAreaOACrisis, &ui_font_Hack12, LV_PART_MAIN | LV_STATE_DEFAULT);


    lv_obj_set_style_text_font(ui_TextAreaOACrisis, &ui_font_Hack10, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

    ui_LabelButtonEMER = lv_label_create(ui_ScreenOACrisis);
    lv_obj_set_width(ui_LabelButtonEMER, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelButtonEMER, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelButtonEMER, -82);
    lv_obj_set_y(ui_LabelButtonEMER, 97);
    lv_obj_set_align(ui_LabelButtonEMER, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelButtonEMER, "Notfall / Unfall\nan Krisenstab melden");
    lv_obj_set_style_text_align(ui_LabelButtonEMER, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelButtonEMER, &ui_font_Hack12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelButtonCIRE = lv_label_create(ui_ScreenOACrisis);
    lv_obj_set_width(ui_LabelButtonCIRE, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelButtonCIRE, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelButtonCIRE, 80);
    lv_obj_set_y(ui_LabelButtonCIRE, 98);
    lv_obj_set_align(ui_LabelButtonCIRE, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelButtonCIRE, "Andere Nachricht an\nKrisenstab schicken");
    lv_obj_set_style_text_align(ui_LabelButtonCIRE, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelButtonCIRE, &ui_font_Hack12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonOACNav1 = lv_btn_create(ui_ScreenOACrisis);
    lv_obj_set_width(ui_ButtonOACNav1, 50);
    lv_obj_set_height(ui_ButtonOACNav1, 35);
    lv_obj_set_x(ui_ButtonOACNav1, -130);
    lv_obj_set_y(ui_ButtonOACNav1, -87);
    lv_obj_set_align(ui_ButtonOACNav1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonOACNav1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonOACNav1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonOACNav1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonOACNav1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonOACNav2 = lv_btn_create(ui_ScreenOACrisis);
    lv_obj_set_width(ui_ButtonOACNav2, 50);
    lv_obj_set_height(ui_ButtonOACNav2, 35);
    lv_obj_set_x(ui_ButtonOACNav2, -72);
    lv_obj_set_y(ui_ButtonOACNav2, -87);
    lv_obj_set_align(ui_ButtonOACNav2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonOACNav2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonOACNav2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonOACNav2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonOACNav2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonOACNav3 = lv_btn_create(ui_ScreenOACrisis);
    lv_obj_set_width(ui_ButtonOACNav3, 50);
    lv_obj_set_height(ui_ButtonOACNav3, 35);
    lv_obj_set_x(ui_ButtonOACNav3, 75);
    lv_obj_set_y(ui_ButtonOACNav3, -87);
    lv_obj_set_align(ui_ButtonOACNav3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonOACNav3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonOACNav3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonOACNav3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonOACNav3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonOACNav4 = lv_btn_create(ui_ScreenOACrisis);
    lv_obj_set_width(ui_ButtonOACNav4, 50);
    lv_obj_set_height(ui_ButtonOACNav4, 35);
    lv_obj_set_x(ui_ButtonOACNav4, 131);
    lv_obj_set_y(ui_ButtonOACNav4, -87);
    lv_obj_set_align(ui_ButtonOACNav4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonOACNav4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonOACNav4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonOACNav4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonOACNav4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OACTextNum = lv_label_create(ui_ScreenOACrisis);
    lv_obj_set_width(ui_OACTextNum, 90);
    lv_obj_set_height(ui_OACTextNum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OACTextNum, 1);
    lv_obj_set_y(ui_OACTextNum, -86);
    lv_obj_set_align(ui_OACTextNum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OACTextNum, "0 von 0");
    lv_obj_set_style_text_align(ui_OACTextNum, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelOACNav1 = lv_label_create(ui_ScreenOACrisis);
    lv_obj_set_width(ui_LabelOACNav1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelOACNav1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelOACNav1, -132);
    lv_obj_set_y(ui_LabelOACNav1, -86);
    lv_obj_set_align(ui_LabelOACNav1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelOACNav1, "<<");
    lv_obj_set_style_text_color(ui_LabelOACNav1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelOACNav1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelOACNav2 = lv_label_create(ui_ScreenOACrisis);
    lv_obj_set_width(ui_LabelOACNav2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelOACNav2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelOACNav2, -74);
    lv_obj_set_y(ui_LabelOACNav2, -86);
    lv_obj_set_align(ui_LabelOACNav2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelOACNav2, "<");
    lv_obj_set_style_text_color(ui_LabelOACNav2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelOACNav2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelOACNav3 = lv_label_create(ui_ScreenOACrisis);
    lv_obj_set_width(ui_LabelOACNav3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelOACNav3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelOACNav3, 77);
    lv_obj_set_y(ui_LabelOACNav3, -86);
    lv_obj_set_align(ui_LabelOACNav3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelOACNav3, ">");
    lv_obj_set_style_text_color(ui_LabelOACNav3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelOACNav3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelOACNav4 = lv_label_create(ui_ScreenOACrisis);
    lv_obj_set_width(ui_LabelOACNav4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelOACNav4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelOACNav4, 133);
    lv_obj_set_y(ui_LabelOACNav4, -86);
    lv_obj_set_align(ui_LabelOACNav4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelOACNav4, ">>");
    lv_obj_set_style_text_color(ui_LabelOACNav4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelOACNav4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);


}
