// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: ROLORAN_TDeck_Neuhaus

#include "ui.h"

void ui_ScreenEMER_screen_init(void)
{
    ui_ScreenEMER = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenEMER, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonEMERSubmit = lv_btn_create(ui_ScreenEMER);
    lv_obj_set_width(ui_ButtonEMERSubmit, 100);
    lv_obj_set_height(ui_ButtonEMERSubmit, 50);
    lv_obj_set_x(ui_ButtonEMERSubmit, -100);
    lv_obj_set_y(ui_ButtonEMERSubmit, 89);
    lv_obj_set_align(ui_ButtonEMERSubmit, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonEMERSubmit, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonEMERSubmit, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonEMERSubmit, lv_color_hex(0xE04646), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonEMERSubmit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonEMERAbort = lv_btn_create(ui_ScreenEMER);
    lv_obj_set_width(ui_ButtonEMERAbort, 100);
    lv_obj_set_height(ui_ButtonEMERAbort, 50);
    lv_obj_set_x(ui_ButtonEMERAbort, 103);
    lv_obj_set_y(ui_ButtonEMERAbort, 89);
    lv_obj_set_align(ui_ButtonEMERAbort, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonEMERAbort, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonEMERAbort, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonEMERAbort, lv_color_hex(0x635F5F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonEMERAbort, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelEMERButtonSubmit = lv_label_create(ui_ScreenEMER);
    lv_obj_set_width(ui_LabelEMERButtonSubmit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelEMERButtonSubmit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelEMERButtonSubmit, -102);
    lv_obj_set_y(ui_LabelEMERButtonSubmit, 89);
    lv_obj_set_align(ui_LabelEMERButtonSubmit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelEMERButtonSubmit, "Weiter");
    lv_obj_set_style_text_font(ui_LabelEMERButtonSubmit, &ui_font_Hack14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelEMERButtonAbort = lv_label_create(ui_ScreenEMER);
    lv_obj_set_width(ui_LabelEMERButtonAbort, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelEMERButtonAbort, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelEMERButtonAbort, 103);
    lv_obj_set_y(ui_LabelEMERButtonAbort, 91);
    lv_obj_set_align(ui_LabelEMERButtonAbort, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelEMERButtonAbort, "Abbrechen");
    lv_obj_set_style_text_font(ui_LabelEMERButtonAbort, &ui_font_Hack14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelEMERHeader = lv_label_create(ui_ScreenEMER);
    lv_obj_set_width(ui_LabelEMERHeader, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelEMERHeader, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelEMERHeader, 0);
    lv_obj_set_y(ui_LabelEMERHeader, -108);
    lv_obj_set_align(ui_LabelEMERHeader, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelEMERHeader, "Notfall / Unfall melden");
    lv_obj_set_style_text_color(ui_LabelEMERHeader, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelEMERHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelEMERHeader, &ui_font_Hack14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextAreaEMERWho = lv_textarea_create(ui_ScreenEMER);
    lv_obj_set_width(ui_TextAreaEMERWho, 169);
    lv_obj_set_height(ui_TextAreaEMERWho, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_TextAreaEMERWho, 66);
    lv_obj_set_y(ui_TextAreaEMERWho, -77);
    lv_obj_set_align(ui_TextAreaEMERWho, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_TextAreaEMERWho, 50);
    lv_textarea_set_placeholder_text(ui_TextAreaEMERWho, "Nachname Vorname");
    lv_textarea_set_one_line(ui_TextAreaEMERWho, true);


    lv_obj_set_style_text_font(ui_TextAreaEMERWho, &ui_font_Hack12, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

    ui_TextAreaEMERWhere = lv_textarea_create(ui_ScreenEMER);
    lv_obj_set_width(ui_TextAreaEMERWhere, 169);
    lv_obj_set_height(ui_TextAreaEMERWhere, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_TextAreaEMERWhere, 66);
    lv_obj_set_y(ui_TextAreaEMERWhere, -38);
    lv_obj_set_align(ui_TextAreaEMERWhere, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_TextAreaEMERWhere, 50);
    lv_textarea_set_placeholder_text(ui_TextAreaEMERWhere, "z.B. Straße Hausnummer");
    lv_textarea_set_one_line(ui_TextAreaEMERWhere, true);


    lv_obj_set_style_text_font(ui_TextAreaEMERWhere, &ui_font_Hack12, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

    ui_TextAreaEMERWhat = lv_textarea_create(ui_ScreenEMER);
    lv_obj_set_width(ui_TextAreaEMERWhat, 165);
    lv_obj_set_height(ui_TextAreaEMERWhat, lv_pct(28));
    lv_obj_set_x(ui_TextAreaEMERWhat, 64);
    lv_obj_set_y(ui_TextAreaEMERWhat, 19);
    lv_obj_set_align(ui_TextAreaEMERWhat, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_TextAreaEMERWhat, 100);
    lv_textarea_set_placeholder_text(ui_TextAreaEMERWhat, "z.B. Herzinfarkt Seniorin, 85, nicht ansprechbar");


    lv_obj_set_style_text_font(ui_TextAreaEMERWhat, &ui_font_Hack12, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

    ui_LabelEMERWho = lv_label_create(ui_ScreenEMER);
    lv_obj_set_width(ui_LabelEMERWho, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelEMERWho, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelEMERWho, -61);
    lv_obj_set_y(ui_LabelEMERWho, -78);
    lv_obj_set_align(ui_LabelEMERWho, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelEMERWho, "Wer meldet?");
    lv_obj_set_style_text_font(ui_LabelEMERWho, &ui_font_Hack12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelEMERWhere = lv_label_create(ui_ScreenEMER);
    lv_obj_set_width(ui_LabelEMERWhere, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelEMERWhere, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelEMERWhere, -90);
    lv_obj_set_y(ui_LabelEMERWhere, -36);
    lv_obj_set_align(ui_LabelEMERWhere, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelEMERWhere, "Wo ist der Notfall?");
    lv_obj_set_style_text_font(ui_LabelEMERWhere, &ui_font_Hack12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelEMERWhat = lv_label_create(ui_ScreenEMER);
    lv_obj_set_width(ui_LabelEMERWhat, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelEMERWhat, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelEMERWhat, -84);
    lv_obj_set_y(ui_LabelEMERWhat, 1);
    lv_obj_set_align(ui_LabelEMERWhat, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelEMERWhat, "Was ist passiert?");
    lv_obj_set_style_text_font(ui_LabelEMERWhat, &ui_font_Hack12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_ScreenEMER);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -74);
    lv_obj_set_y(ui_Label1, 30);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "max. 100 Zeichen");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_Hack10, LV_PART_MAIN | LV_STATE_DEFAULT);


}
