// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: ROLORAN_TDeck_Neuhaus

#include "ui.h"

void ui_ScreenOANonCrisis_screen_init(void)
{
    ui_ScreenOANonCrisis = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenOANonCrisis, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelOANonCrisis = lv_label_create(ui_ScreenOANonCrisis);
    lv_obj_set_width(ui_LabelOANonCrisis, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelOANonCrisis, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelOANonCrisis, 0);
    lv_obj_set_y(ui_LabelOANonCrisis, -114);
    lv_obj_set_align(ui_LabelOANonCrisis, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelOANonCrisis, "Gemeinde Neuhaus           Amtliche Kurzmitteilungen");
    lv_obj_set_style_text_color(ui_LabelOANonCrisis, lv_color_hex(0x00FA73), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelOANonCrisis, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelOANonCrisis, &ui_font_Hack10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextAreaOANonCrisis = lv_textarea_create(ui_ScreenOANonCrisis);
    lv_obj_set_width(ui_TextAreaOANonCrisis, 307);
    lv_obj_set_height(ui_TextAreaOANonCrisis, 176);
    lv_obj_set_x(ui_TextAreaOANonCrisis, 0);
    lv_obj_set_y(ui_TextAreaOANonCrisis, 25);
    lv_obj_set_align(ui_TextAreaOANonCrisis, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextAreaOANonCrisis, "Hier wird die jeweilige Nachricht angezeigt.");
    lv_obj_set_style_text_font(ui_TextAreaOANonCrisis, &ui_font_Hack12, LV_PART_MAIN | LV_STATE_DEFAULT);


    lv_obj_set_style_text_color(ui_TextAreaOANonCrisis, lv_color_hex(0x808080),
                                LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextAreaOANonCrisis, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextAreaOANonCrisis, &ui_font_Hack10, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

    ui_ButtonOANCNav1 = lv_btn_create(ui_ScreenOANonCrisis);
    lv_obj_set_width(ui_ButtonOANCNav1, 50);
    lv_obj_set_height(ui_ButtonOANCNav1, 35);
    lv_obj_set_x(ui_ButtonOANCNav1, -130);
    lv_obj_set_y(ui_ButtonOANCNav1, -87);
    lv_obj_set_align(ui_ButtonOANCNav1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonOANCNav1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonOANCNav1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonOANCNav1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonOANCNav1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonOANCNav2 = lv_btn_create(ui_ScreenOANonCrisis);
    lv_obj_set_width(ui_ButtonOANCNav2, 50);
    lv_obj_set_height(ui_ButtonOANCNav2, 35);
    lv_obj_set_x(ui_ButtonOANCNav2, -72);
    lv_obj_set_y(ui_ButtonOANCNav2, -87);
    lv_obj_set_align(ui_ButtonOANCNav2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonOANCNav2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonOANCNav2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonOANCNav2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonOANCNav2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonOANCNav3 = lv_btn_create(ui_ScreenOANonCrisis);
    lv_obj_set_width(ui_ButtonOANCNav3, 50);
    lv_obj_set_height(ui_ButtonOANCNav3, 35);
    lv_obj_set_x(ui_ButtonOANCNav3, 75);
    lv_obj_set_y(ui_ButtonOANCNav3, -87);
    lv_obj_set_align(ui_ButtonOANCNav3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonOANCNav3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonOANCNav3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonOANCNav3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonOANCNav3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonOANCNav4 = lv_btn_create(ui_ScreenOANonCrisis);
    lv_obj_set_width(ui_ButtonOANCNav4, 50);
    lv_obj_set_height(ui_ButtonOANCNav4, 35);
    lv_obj_set_x(ui_ButtonOANCNav4, 131);
    lv_obj_set_y(ui_ButtonOANCNav4, -87);
    lv_obj_set_align(ui_ButtonOANCNav4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonOANCNav4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonOANCNav4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonOANCNav4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonOANCNav4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelOANCNav1 = lv_label_create(ui_ScreenOANonCrisis);
    lv_obj_set_width(ui_LabelOANCNav1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelOANCNav1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelOANCNav1, -132);
    lv_obj_set_y(ui_LabelOANCNav1, -86);
    lv_obj_set_align(ui_LabelOANCNav1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelOANCNav1, "<<");
    lv_obj_set_style_text_color(ui_LabelOANCNav1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelOANCNav1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelOANCNav2 = lv_label_create(ui_ScreenOANonCrisis);
    lv_obj_set_width(ui_LabelOANCNav2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelOANCNav2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelOANCNav2, -74);
    lv_obj_set_y(ui_LabelOANCNav2, -86);
    lv_obj_set_align(ui_LabelOANCNav2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelOANCNav2, "<");
    lv_obj_set_style_text_color(ui_LabelOANCNav2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelOANCNav2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelOANCNav3 = lv_label_create(ui_ScreenOANonCrisis);
    lv_obj_set_width(ui_LabelOANCNav3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelOANCNav3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelOANCNav3, 77);
    lv_obj_set_y(ui_LabelOANCNav3, -86);
    lv_obj_set_align(ui_LabelOANCNav3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelOANCNav3, ">");
    lv_obj_set_style_text_color(ui_LabelOANCNav3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelOANCNav3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelOANCNav4 = lv_label_create(ui_ScreenOANonCrisis);
    lv_obj_set_width(ui_LabelOANCNav4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelOANCNav4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelOANCNav4, 133);
    lv_obj_set_y(ui_LabelOANCNav4, -86);
    lv_obj_set_align(ui_LabelOANCNav4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelOANCNav4, ">>");
    lv_obj_set_style_text_color(ui_LabelOANCNav4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelOANCNav4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OANCTextNum = lv_label_create(ui_ScreenOANonCrisis);
    lv_obj_set_width(ui_OANCTextNum, 90);
    lv_obj_set_height(ui_OANCTextNum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OANCTextNum, 1);
    lv_obj_set_y(ui_OANCTextNum, -86);
    lv_obj_set_align(ui_OANCTextNum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OANCTextNum, "0 von 0");
    lv_obj_set_style_text_align(ui_OANCTextNum, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);


}
