// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: ROLORAN_TDeck_Neuhaus

#include "ui.h"

void ui_ScreenEMER2_screen_init(void)
{
    ui_ScreenEMER2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenEMER2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonEMERSubmit1 = lv_btn_create(ui_ScreenEMER2);
    lv_obj_set_width(ui_ButtonEMERSubmit1, 100);
    lv_obj_set_height(ui_ButtonEMERSubmit1, 50);
    lv_obj_set_x(ui_ButtonEMERSubmit1, -100);
    lv_obj_set_y(ui_ButtonEMERSubmit1, 89);
    lv_obj_set_align(ui_ButtonEMERSubmit1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonEMERSubmit1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonEMERSubmit1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonEMERSubmit1, lv_color_hex(0xE04646), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonEMERSubmit1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonEMERAbort1 = lv_btn_create(ui_ScreenEMER2);
    lv_obj_set_width(ui_ButtonEMERAbort1, 100);
    lv_obj_set_height(ui_ButtonEMERAbort1, 50);
    lv_obj_set_x(ui_ButtonEMERAbort1, 103);
    lv_obj_set_y(ui_ButtonEMERAbort1, 89);
    lv_obj_set_align(ui_ButtonEMERAbort1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonEMERAbort1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonEMERAbort1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonEMERAbort1, lv_color_hex(0x635F5F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonEMERAbort1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelEMERButtonSubmit1 = lv_label_create(ui_ScreenEMER2);
    lv_obj_set_width(ui_LabelEMERButtonSubmit1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelEMERButtonSubmit1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelEMERButtonSubmit1, -102);
    lv_obj_set_y(ui_LabelEMERButtonSubmit1, 89);
    lv_obj_set_align(ui_LabelEMERButtonSubmit1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelEMERButtonSubmit1, "Meldung\nabsenden");
    lv_obj_set_style_text_align(ui_LabelEMERButtonSubmit1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelEMERButtonSubmit1, &ui_font_Hack14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelEMERButtonAbort1 = lv_label_create(ui_ScreenEMER2);
    lv_obj_set_width(ui_LabelEMERButtonAbort1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelEMERButtonAbort1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelEMERButtonAbort1, 103);
    lv_obj_set_y(ui_LabelEMERButtonAbort1, 91);
    lv_obj_set_align(ui_LabelEMERButtonAbort1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelEMERButtonAbort1, "Abbrechen");
    lv_obj_set_style_text_font(ui_LabelEMERButtonAbort1, &ui_font_Hack14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelEMERHeader1 = lv_label_create(ui_ScreenEMER2);
    lv_obj_set_width(ui_LabelEMERHeader1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelEMERHeader1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelEMERHeader1, 0);
    lv_obj_set_y(ui_LabelEMERHeader1, -108);
    lv_obj_set_align(ui_LabelEMERHeader1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelEMERHeader1, "Notfall / Unfall melden");
    lv_obj_set_style_text_color(ui_LabelEMERHeader1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelEMERHeader1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelEMERHeader1, &ui_font_Hack14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CIRE2SwitchLebensbedrohlich = lv_switch_create(ui_ScreenEMER2);
    lv_obj_set_width(ui_CIRE2SwitchLebensbedrohlich, 50);
    lv_obj_set_height(ui_CIRE2SwitchLebensbedrohlich, 25);
    lv_obj_set_x(ui_CIRE2SwitchLebensbedrohlich, -122);
    lv_obj_set_y(ui_CIRE2SwitchLebensbedrohlich, -1);
    lv_obj_set_align(ui_CIRE2SwitchLebensbedrohlich, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_CIRE2SwitchLebensbedrohlich, LV_STATE_CHECKED);       /// States


    ui_Label2 = lv_label_create(ui_ScreenEMER2);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 38);
    lv_obj_set_y(ui_Label2, 0);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Lebensgefahr (mind. 1 Person)");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xF80606), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dropdown2 = lv_dropdown_create(ui_ScreenEMER2);
    lv_dropdown_set_options(ui_Dropdown2, "1\n2\n3\nmehr als 3");
    lv_obj_set_width(ui_Dropdown2, 150);
    lv_obj_set_height(ui_Dropdown2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown2, 2);
    lv_obj_set_y(ui_Dropdown2, -42);
    lv_obj_set_align(ui_Dropdown2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_CIRE2SwitchErsthelfer = lv_switch_create(ui_ScreenEMER2);
    lv_obj_set_width(ui_CIRE2SwitchErsthelfer, 50);
    lv_obj_set_height(ui_CIRE2SwitchErsthelfer, 25);
    lv_obj_set_x(ui_CIRE2SwitchErsthelfer, -122);
    lv_obj_set_y(ui_CIRE2SwitchErsthelfer, 39);
    lv_obj_set_align(ui_CIRE2SwitchErsthelfer, LV_ALIGN_CENTER);


    ui_Label3 = lv_label_create(ui_ScreenEMER2);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 42);
    lv_obj_set_y(ui_Label3, 38);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Ausgebild. Ersthelfer ist vor Ort");

    ui_Label4 = lv_label_create(ui_ScreenEMER2);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 2);
    lv_obj_set_y(ui_Label4, -76);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Wie viele Personen sind betroffen?");


}
