// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: ROLORAN_TDeck_Neuhaus

#include "ui.h"

void ui_ScreenCIRE_screen_init(void)
{
    ui_ScreenCIRE = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenCIRE, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelCIREHeader = lv_label_create(ui_ScreenCIRE);
    lv_obj_set_width(ui_LabelCIREHeader, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCIREHeader, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCIREHeader, 2);
    lv_obj_set_y(ui_LabelCIREHeader, -111);
    lv_obj_set_align(ui_LabelCIREHeader, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCIREHeader, "Meldung an Krisenstab schicken");
    lv_obj_set_style_text_color(ui_LabelCIREHeader, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelCIREHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelCIREHeader, &ui_font_Hack12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonCIREsubmit = lv_btn_create(ui_ScreenCIRE);
    lv_obj_set_width(ui_ButtonCIREsubmit, 100);
    lv_obj_set_height(ui_ButtonCIREsubmit, 50);
    lv_obj_set_x(ui_ButtonCIREsubmit, -99);
    lv_obj_set_y(ui_ButtonCIREsubmit, 89);
    lv_obj_set_align(ui_ButtonCIREsubmit, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonCIREsubmit, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonCIREsubmit, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonCIREabort = lv_btn_create(ui_ScreenCIRE);
    lv_obj_set_width(ui_ButtonCIREabort, 100);
    lv_obj_set_height(ui_ButtonCIREabort, 50);
    lv_obj_set_x(ui_ButtonCIREabort, 101);
    lv_obj_set_y(ui_ButtonCIREabort, 89);
    lv_obj_set_align(ui_ButtonCIREabort, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonCIREabort, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonCIREabort, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonCIREabort, lv_color_hex(0x625D5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonCIREabort, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelButtonCIREsubmit = lv_label_create(ui_ScreenCIRE);
    lv_obj_set_width(ui_LabelButtonCIREsubmit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelButtonCIREsubmit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelButtonCIREsubmit, -99);
    lv_obj_set_y(ui_LabelButtonCIREsubmit, 90);
    lv_obj_set_align(ui_LabelButtonCIREsubmit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelButtonCIREsubmit, "Absenden");
    lv_obj_set_style_text_font(ui_LabelButtonCIREsubmit, &ui_font_Hack14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelButtonCIREabort = lv_label_create(ui_ScreenCIRE);
    lv_obj_set_width(ui_LabelButtonCIREabort, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelButtonCIREabort, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelButtonCIREabort, 102);
    lv_obj_set_y(ui_LabelButtonCIREabort, 90);
    lv_obj_set_align(ui_LabelButtonCIREabort, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelButtonCIREabort, "Abbrechen");
    lv_obj_set_style_text_font(ui_LabelButtonCIREabort, &ui_font_Hack14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelCIREWho = lv_label_create(ui_ScreenCIRE);
    lv_obj_set_width(ui_LabelCIREWho, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCIREWho, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCIREWho, -102);
    lv_obj_set_y(ui_LabelCIREWho, -78);
    lv_obj_set_align(ui_LabelCIREWho, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCIREWho, "Wer meldet?");
    lv_obj_set_style_text_font(ui_LabelCIREWho, &ui_font_Hack14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelCIRECategory = lv_label_create(ui_ScreenCIRE);
    lv_obj_set_width(ui_LabelCIRECategory, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCIRECategory, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCIRECategory, -106);
    lv_obj_set_y(ui_LabelCIRECategory, -42);
    lv_obj_set_align(ui_LabelCIRECategory, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCIRECategory, "Kategorie:");
    lv_obj_set_style_text_font(ui_LabelCIRECategory, &ui_font_Hack14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelCIREFreetext = lv_label_create(ui_ScreenCIRE);
    lv_obj_set_width(ui_LabelCIREFreetext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCIREFreetext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCIREFreetext, -29);
    lv_obj_set_y(ui_LabelCIREFreetext, -8);
    lv_obj_set_align(ui_LabelCIREFreetext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCIREFreetext, "Nachricht (max. 100 Zeichen):");
    lv_obj_set_style_text_font(ui_LabelCIREFreetext, &ui_font_Hack14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextAreaCIREFreetext = lv_textarea_create(ui_ScreenCIRE);
    lv_obj_set_width(ui_TextAreaCIREFreetext, 298);
    lv_obj_set_height(ui_TextAreaCIREFreetext, 50);
    lv_obj_set_x(ui_TextAreaCIREFreetext, 0);
    lv_obj_set_y(ui_TextAreaCIREFreetext, 29);
    lv_obj_set_align(ui_TextAreaCIREFreetext, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_TextAreaCIREFreetext, 100);
    lv_textarea_set_placeholder_text(ui_TextAreaCIREFreetext, "Hier Nachricht eingeben...");
    lv_obj_set_style_text_font(ui_TextAreaCIREFreetext, &ui_font_Hack14, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_TextAreaCIREWho = lv_textarea_create(ui_ScreenCIRE);
    lv_obj_set_width(ui_TextAreaCIREWho, 189);
    lv_obj_set_height(ui_TextAreaCIREWho, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_TextAreaCIREWho, 52);
    lv_obj_set_y(ui_TextAreaCIREWho, -80);
    lv_obj_set_align(ui_TextAreaCIREWho, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextAreaCIREWho, "Nachname Vorname");
    lv_textarea_set_one_line(ui_TextAreaCIREWho, true);


    lv_obj_set_style_text_font(ui_TextAreaCIREWho, &ui_font_Hack14, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

    ui_DropdownCIRECategory = lv_dropdown_create(ui_ScreenCIRE);
    lv_dropdown_set_options(ui_DropdownCIRECategory,
                            "Anfrage an Krisenstab\nBedarf Arzt / Pflege\nBedarf Betriebsmittel\nBedarf Lebensmittel\nBedarf Medikamente\nMeldung von Gefahr\nMeldung von Schaden\nRückfrage zu Mitteilung\nSonstiges");
    lv_obj_set_width(ui_DropdownCIRECategory, 189);
    lv_obj_set_height(ui_DropdownCIRECategory, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DropdownCIRECategory, 51);
    lv_obj_set_y(ui_DropdownCIRECategory, -43);
    lv_obj_set_align(ui_DropdownCIRECategory, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DropdownCIRECategory, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_DropdownCIRECategory, &ui_font_Hack12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_DropdownCIRECategory, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_DropdownCIRECategory), &ui_font_Hack14,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_DropdownCIRECategory), &ui_font_Hack14,
                               LV_PART_SELECTED | LV_STATE_DEFAULT);


}
