// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: ROLORAN_TDeck_Neuhaus

#include "ui.h"

void ui_ScreenMaintenance_screen_init(void)
{
    ui_ScreenMaintenance = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenMaintenance, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelMaintenanceMiddle = lv_label_create(ui_ScreenMaintenance);
    lv_obj_set_width(ui_LabelMaintenanceMiddle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMaintenanceMiddle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMaintenanceMiddle, -2);
    lv_obj_set_y(ui_LabelMaintenanceMiddle, -39);
    lv_obj_set_align(ui_LabelMaintenanceMiddle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMaintenanceMiddle, "Bitte starten Sie diesen Apparat neu!");
    lv_obj_set_style_text_font(ui_LabelMaintenanceMiddle, &ui_font_Hack14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMaintenanceTop = lv_label_create(ui_ScreenMaintenance);
    lv_obj_set_width(ui_LabelMaintenanceTop, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMaintenanceTop, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMaintenanceTop, 2);
    lv_obj_set_y(ui_LabelMaintenanceTop, -104);
    lv_obj_set_align(ui_LabelMaintenanceTop, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMaintenanceTop, "Wartungsmodus");
    lv_obj_set_style_text_color(ui_LabelMaintenanceTop, lv_color_hex(0x00D0FE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMaintenanceTop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMaintenanceTop, &ui_font_Hack14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMaintenanceBottom = lv_label_create(ui_ScreenMaintenance);
    lv_obj_set_width(ui_LabelMaintenanceBottom, lv_pct(87));
    lv_obj_set_height(ui_LabelMaintenanceBottom, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMaintenanceBottom, 0);
    lv_obj_set_y(ui_LabelMaintenanceBottom, 36);
    lv_obj_set_align(ui_LabelMaintenanceBottom, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMaintenanceBottom,
                      "Zum Neustart unterbrechen Sie bitte die Stromversorgung und stellen diese nach einigen Sekunden wieder her.");
    lv_obj_set_style_text_align(ui_LabelMaintenanceBottom, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMaintenanceBottom, &ui_font_Hack12, LV_PART_MAIN | LV_STATE_DEFAULT);


}
