// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: ROLORAN_TDeck_Neuhaus

#include "ui.h"

void ui_ScreenProvisioning_screen_init(void)
{
    ui_ScreenProvisioning = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenProvisioning, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelProvisioningMiddle = lv_label_create(ui_ScreenProvisioning);
    lv_obj_set_width(ui_LabelProvisioningMiddle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelProvisioningMiddle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelProvisioningMiddle, -2);
    lv_obj_set_y(ui_LabelProvisioningMiddle, -47);
    lv_obj_set_align(ui_LabelProvisioningMiddle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelProvisioningMiddle,
                      "Bitte geben Sie diesen Apparat\nan die Gemeinde oder einen\nbeauftragten Betreiber!");
    lv_obj_set_style_text_align(ui_LabelProvisioningMiddle, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelProvisioningMiddle, &ui_font_Hack14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelProvisioningTop = lv_label_create(ui_ScreenProvisioning);
    lv_obj_set_width(ui_LabelProvisioningTop, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelProvisioningTop, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelProvisioningTop, 2);
    lv_obj_set_y(ui_LabelProvisioningTop, -104);
    lv_obj_set_align(ui_LabelProvisioningTop, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelProvisioningTop, "Apparat muss eingerichtet werden");
    lv_obj_set_style_text_color(ui_LabelProvisioningTop, lv_color_hex(0x00D0FE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelProvisioningTop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelProvisioningTop, &ui_font_Hack14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelProvisioningBottom = lv_label_create(ui_ScreenProvisioning);
    lv_obj_set_width(ui_LabelProvisioningBottom, lv_pct(87));
    lv_obj_set_height(ui_LabelProvisioningBottom, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelProvisioningBottom, 0);
    lv_obj_set_y(ui_LabelProvisioningBottom, 55);
    lv_obj_set_align(ui_LabelProvisioningBottom, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelProvisioningBottom,
                      "Dieser Pager kann erst verwendet\nwerden, wenn von zentraler Stelle\nalle grundlegenden Einstellungen\nneu vorgenommen worden sind.\n\nDie aktuelle Einsatzbereitschaft \nist stark begrenzt.");
    lv_obj_set_style_text_align(ui_LabelProvisioningBottom, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelProvisioningBottom, &ui_font_Hack12, LV_PART_MAIN | LV_STATE_DEFAULT);


}
