// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: ROLORAN_TDeck_Neuhaus

#include "ui.h"

void ui_ScreenEULA_screen_init(void)
{
    ui_ScreenEULA = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenEULA, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelMaintenanceMiddle1 = lv_label_create(ui_ScreenEULA);
    lv_obj_set_width(ui_LabelMaintenanceMiddle1, lv_pct(95));
    lv_obj_set_height(ui_LabelMaintenanceMiddle1, lv_pct(76));
    lv_obj_set_x(ui_LabelMaintenanceMiddle1, -1);
    lv_obj_set_y(ui_LabelMaintenanceMiddle1, -5);
    lv_obj_set_align(ui_LabelMaintenanceMiddle1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMaintenanceMiddle1,
                      "Bitte nutzen Sie zur Kommunikation mit der Gemeinde und Rettungsdiensten \nimmer Telefon, Mobilfunk oder Internet, \nsoweit diese noch funktionieren.\n\nDieser Pager dient der Anzeige amtlicher Kurzmitteilungen und kann nur im Krisenfall genutzt werden, um kurze Nachrichten an den Krisenstab der Gemeinde zu schicken.\nEr sollte dazu nur verwendet werden, wenn die restliche Kommunikationsinfrastruktur ausgefallen ist oder nicht genutzt werden kann.");
    lv_obj_set_style_text_align(ui_LabelMaintenanceMiddle1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMaintenanceMiddle1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelEULA1 = lv_label_create(ui_ScreenEULA);
    lv_obj_set_width(ui_LabelEULA1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelEULA1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelEULA1, 2);
    lv_obj_set_y(ui_LabelEULA1, -112);
    lv_obj_set_align(ui_LabelEULA1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelEULA1, "Wichtiger Hinweis");
    lv_obj_set_style_text_color(ui_LabelEULA1, lv_color_hex(0x00D0FE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelEULA1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelEULA1, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EULAokButton = lv_btn_create(ui_ScreenEULA);
    lv_obj_set_width(ui_EULAokButton, 288);
    lv_obj_set_height(ui_EULAokButton, 22);
    lv_obj_set_x(ui_EULAokButton, 0);
    lv_obj_set_y(ui_EULAokButton, 102);
    lv_obj_set_align(ui_EULAokButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_EULAokButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_EULAokButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_ScreenEULA);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -6);
    lv_obj_set_y(ui_Label5, 102);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "OK");


}
