// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: ROLORAN_TDeck_Neuhaus

#include "ui.h"

void ui_ScreenSplash_screen_init(void)
{
    ui_ScreenSplash = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenSplash, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelSplashBackground = lv_obj_create(ui_ScreenSplash);
    lv_obj_set_width(ui_PanelSplashBackground, 340);
    lv_obj_set_height(ui_PanelSplashBackground, 255);
    lv_obj_set_x(ui_PanelSplashBackground, 2);
    lv_obj_set_y(ui_PanelSplashBackground, -4);
    lv_obj_set_align(ui_PanelSplashBackground, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelSplashBackground, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelSplashBackground, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSplashBackground, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_PanelSplashBackground, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_PanelSplashBackground, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageSplashLogo = lv_img_create(ui_ScreenSplash);
    lv_img_set_src(ui_ImageSplashLogo, &ui_img_neuhaus_logo_png);
    lv_obj_set_width(ui_ImageSplashLogo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageSplashLogo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageSplashLogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageSplashLogo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageSplashLogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags


}
